language: generic
os: linux
dist: bionic
services: [mysql, postgresql]
branches:
    except: [gh-pages]
git:
    depth: 1
addons:
  apt:
      update: true
      packages:
          - erlang
          - fpc
          - gawk
          - lua5.3
          - mono-devel
          - nim
          - r-base
          - rakudo
          - rustc
          - sqlite3
          - zsh
  snaps:
      - name: julia
        confinement: classic
      - name: kotlin
        confinement: classic
env:
    global:
        - PERL5LIB="$HOME/.local/share/perl5/lib/perl5"
        - PATH="$PATH:/usr/lib/dart/bin:$TRAVIS_BUILD_DIR/node_modules/.bin"
before_install:
    - |
        wget -q https://downloads.lightbend.com/scala/2.13.4/scala-2.13.4.deb
        sudo -E dpkg -i "${_##*/}"
    - |
        wget -q http://downloads.dlang.org/releases/2021/dmd_2.095.0-0_amd64.deb
        sudo -E dpkg -i "${_##*/}"
    - |
        wget -q https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.10.5-1_amd64.deb
        sudo -E dpkg -i "${_##*/}"
    - yarn add @types/node coffeescript livescript ts-node typescript
install:
    - cpanm -qnl ~/.local/share/perl5 JSON::Parse
before_script:
    - |
        psql -c 'DROP DATABASE IF EXISTS "7SegmentDisplays";'
        psql -c 'CREATE DATABASE "7SegmentDisplays";'
    - |
        mysql -e 'CREATE DATABASE IF NOT EXISTS 7SegmentDisplays;'
        mysql -e 'SET GLOBAL local_infile = 1;'
script:
    - make all test
before_deploy:
    - |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb
        sudo -E dpkg -i "${_##*/}"
    - make bench
deploy:
    provider: pages
    strategy: git
    cleanup: false
    keep_history: false
    email: deploy@travis-ci.org
    name: Deployment Bot
    commit_message: Deploy %{target_branch}
    token:
        secure: "KXMurcS8Oj3UYgZXM8sfTijLGJkBQqCxkE1MMpB9EkvOlrjfo+LiDT4UCGt1yHgo3YCWFQuxvgrTowy5BxJBrJUU8pHZFjZ/I26YQDRw5QO+AbRNIUpnTBHMjACycCHwY9bfDxAfj0y7Sru6PadWMfS9Jlsnmr1ufK1njZOIgTxc9J7pCOLkPjcQNEorewjuZK9BsYE7ffrg5IIXWUPuTeNmpa3C8bYXD/FE4PN6I72a7BMzFS/a/j4ZkIFj12M126e3JZb+Ng9j5crFyCGmbfvsZgkZcZxt86ykuyJzHtJNUsCPuRHl8Xc21mxCtcksenl/4voiGnCKj0+8nkyjI91J80+SeGxAP63psWcL69Tu341wDD+38h4ezZP7aWcQHMOEXQGtXx6MCwrH5KsM7G+ZGr5leTcQsfzkb/D13tsngXjzvDFxsaB9j+FHkNqfk57ZuXGeJ4re6jrQWMrqsDTDHg1QNF4Rt0gx/3hBTFN7FjAJe4xtP5j4Bi8oezHAMWcJECHod5y4xjDxY/VS+CoEihZyUiHjzo6IKuzw3Jmq4M485BJtJ+OeGATvF77VI2Cky0UNtl39CAcWQR5RzSDnzQGtE0QwO2cTfrscmm4NZwP0FApi7XxdVNKrqXedVnFv2HG/sckRXxWWSJuXKLUHUp+lNhgRFh5jXtEKzMU="
    on:
        branch: master
    edge:
        branch: master
